### PR TITLE
add kusoda.net

### PR DESCRIPTION
**Pull request by Zel9278**
https://kusoda.net
author: me

### CODE REVIEW

**Review by sksat — CHANGES_REQUESTED** [review]
Please create simple diff.
Don't commit garbage(auto formatted by editor?) diff for add one kuso-domain.
We make and want kuso-domain websites, but we have to be honest about the technology for spreading kuso.

**Comment by Zel9278** [comment]
sorry, i fix commit

**Review by sksat — APPROVED** [review]
Thanks. LGTM.

FYI: When you're deleting a truly pointless commit like this, it's often better to rebase it and re-commit it, unless it's already been merged. Also, since this project uses `yarn`, you should avoid using the `npm` without thinking.

**Comment by Zel9278** [comment]
> Thanks. LGTM.
> 
> FYI: When you're deleting a truly pointless commit like this, it's often better to rebase it and re-commit it, unless it's already been merged. Also, since this project uses `yarn`, you should avoid using the `npm` without thinking.

ok, thanks.

**Pull request merged**
